---
- hosts: all
  roles:
    - {role: set_fact}
    - {role: check}
    - {role: hostname}
    - {role: repo}

- hosts: masters,nodes,board,registry,registry,nfs-server
  roles:
    - {role: common}
    - {role: chrony}

- hosts: registry
  roles:
    - {role: docker}
    - {role: registry}
    - {role: push-images}
- hosts: nfs-server
  roles:
    - {role: nfs-server}
    - {role: nfs-client}
- hosts: nodes,board,registry,nfs-server
  roles:
    - {role: ntpd-client}

- hosts: masters,nodes
  roles:
    - {role: docker}
    - {role: load-k8s-images-master}
    - {role: k8s}
    - {role: nfs-client}
    - {role: node}
    - {role: istio.node, tags: istio}
- hosts: masters
  roles:
    - {role: multi_master_commen,  when: groups.masters|length > 1}
    - {role: ntpd-server}
    - {role: master}
    - {role: helm}
    - {role: kubectlCMD}
    - {role: fetch_ca}

   
- hosts: nodes
  roles:
    - {role: copy-addnode-cmd}

- hosts: nodes,master
  roles:
    - istio.common
  tags: istio
- hosts: masters
  roles:
    - {role: istio, tags: istio}
    - {role: heapster}

- hosts: masters
  roles:
    - {role: cordon}

- hosts: board
  roles:
    - {role: docker}
    - {role: board, tags: board}
    - {role: docker-compose, tags: board}
- hosts: jenkins_node
  roles:
    - {role: common}
    - {role: docker}
    - {role: git}

- hosts: masters
  roles:
    - {role: kubeedge-cloud, tags: edge}
    - {role: addtoken, tags: edge}
- hosts: edges
  roles:
   - {role: hostname, tags: edge}
   - {role: kubeedge-edge, tags: edge}

- hosts: masters
  roles:
    - {role: restart-edgecloud, tags: edge}
    - {role: noschedul_edge, tags: edge}
    - {role: noschedul}
