---
- name: install nfs-utils
  yum: name=nfs-utils state=latest
  when: ansible_os_family == "RedHat"
- name: install rpcbind
  yum: name=rpcbind state=latest
  when: ansible_os_family == "RedHat"
- name: install nfs on debian
  shell: dpkg -i {{install_package}}/nfs-debian/*.deb
  when: ansible_os_family == "Debian"

- copy:
    src: "{{role_path}}/files/nfsclient.sh"
    dest: /var/nfsclient.sh
    owner: root
    group: root
    mode: 755
- name: debug nsf_server_ip_address
  debug: "var={{ nsf_server_ip_address }}"
  ignore_errors: yes
- name: run nfs script
  shell: /var/nfsclient.sh {{ nsf_server_ip_address }}
  ignore_errors: yes
  
