---

- name: stop all the container
  shell: docker stop $(docker ps|awk '{print $1}')
  ignore_errors: yes

- name: remove imaages
  shell: docker rmi -f $(docker images|awk '{print $3}')
  ignore_errors: yes
  
- name: install kubelet kubeadm kubectl docker
  yum: name=kubelet,kubeadm,kubectl,docker-ce,docker-ce-cli state=removed
  when: ansible_os_family == "RedHat"
- name: uninstall kubelet kubeadm kubectl docker
  shell: dpkg -P kubeadm kubectl kubelet kubernetes-cni containerd.io docker-ce docker-ce-cli
  when: ansible_os_family == "Debian"

- name: rm -rf docker dir
  shell: rm -rf {{docker_dir}}/*

- name: rm /etc/docker
  file: path={{item}} state=absent mode=755
  with_items:
    - "/etc/docker"
    - "/var/lib/etcd"
    - "/tmp/t.sh"
    - "/tmp/rpm"
    - "/etc/kubernetes/"
    - "/etc/cni/net.d"
- name: delete float ip
  shell: ip addr del {{virt_ip}} dev {{ansible_default_ipv4.alias}} 
  ignore_errors: yes
