---


- name: push image to registry
  shell: docker pull {{registry_ip_address}}:5000/k8simage/{{item}}
  with_items:
    - "pause:3.2"
    - "kube-proxy:{{kubernetesVersion}}"
    - "kube-apiserver:{{kubernetesVersion}}"
    - "kube-scheduler:{{kubernetesVersion}}"
    - "kube-controller-manager:{{kubernetesVersion}}"
    - "coredns:1.6.7"
    - "etcd:3.4.3-0"
    - "flannel:v0.11.0-amd64"
#  shell: /var/lib/sh/run.sh
#  shell: {{shfile_dir}}{{tmp}}{{registry_sh}} {{registy_ip_address}}
#  cmd: {{shfile_dir}}
  
