apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: haproxy
    tier: control-plane
  name: kube-haproxy
  namespace: kube-system
spec:
  hostNetwork: true
  priorityClassName: system-cluster-critical
  containers:
  - name: kube-haproxy
    image: {{registry_ip_address}}:5000/k8simage/haproxy:2.1.0-alpine
    volumeMounts:
    - name: haproxy-cfg
      readOnly: true
      mountPath: /usr/local/etc/haproxy/haproxy.cfg
    resources:
      requests:
        cpu: 100m
  volumes:
  - name: haproxy-cfg
    hostPath:
      path: /etc/kubernetes/kube-haproxy.cfg
      type: FileOrCreate
